### ISSUE TITLE
Time spent in the integrated terminal

### ISSUE THREAD

**Issue by vdolgishev** [hangxingliu/vscode-coding-tracker#7]
Is it possible to add to a chart time that was spent in the integrated terminal?

**Comment by hangxingliu** [comment]
It is a good idea. But it is difficult achieved . Because VS Code has not any useful interface and event around  integrated terminal.
(VS Code only support methods to creating terminal and managing terminal created by you. And an event fired by closing a terminal)
===========
If you have any good ways to achieve this idea. you can contribute your codes or your ways to this repository.
