### ISSUE TITLE
24 hours report for a custom date

### ISSUE THREAD

**Issue by vdolgishev** [hangxingliu/vscode-coding-tracker#8]
Will be great to have a possibility to get 24 hours report for a custom date, not only for last 24 hours.

**Comment by hangxingliu** [comment]
Thanks for your proposal. I think it is a good idea. And I will add it into report page in the next version.   
But It will be release in August. Because I need  finish a commercial project firstly.  

(P.s. Maybe you can have a try by yourself in project <https://github.com/hangxingliu/vscode-coding-tracker-server> . And give this project a pull request)

---
<https://github.com/hangxingliu/vscode-coding-tracker-server/commit/6e19764f77bea184c6791124eba408867cfa66a2>

**Comment by hangxingliu** [comment]
Hello, vdolgishev, I saw your Russian translation pull request in "vscode-coding-tracker-server" repository.   
I believe it would be better if you give this repository a pull request about Russian translation in extension side.

Just create a file: `package.nls.ru.json`. and copy content from `package.nls.json` into it. then translate it.
Finally, this extension will be displayed in Russian when you set up the language of VSCode to Ruassian.

Thanks

**Comment by hangxingliu** [comment]
Added in server side codes. Release in next version
